name: develop build and deploy

on:
  push:
    branches:

env:
  AWS_REGION: ap-northeast-2

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: JDK 21 설치
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: .env 생성
        run: |
          touch ./env
          echo "${{ secrets.ENV }}" > ./.env
        shell: bash
#      - name: application.yml 생성
#        run: |
#          cd ./src/main/resources
#          touch ./application.yml
#          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
#        shell: bash
#      - name: application-prod.yml 생성
#        run: |
#          cd ./src/main/resources
#          touch ./application-prod.yml
#          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./application-prod.yml
#        shell: bash
      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew
      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test
      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/eonedu_cicd .
          docker push ${{ secrets.DOCKER_USERNAME }}/eonedu_cicd
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker ps
            docker pull ${{ secrets.DOCKER_USERNAME }}/eonedu_cicd
            docker stop eonedu_cicd
            sleep 5s
            docker run --rm --name eonedu_cicd -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/eonedu_cicd
            docker image prune -f